"""first version

Revision ID: e48ebb4c2a75
Revises: 
Create Date: 2018-11-15 10:30:43.737502

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils

# revision identifiers, used by Alembic.
revision = 'e48ebb4c2a75'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('access_token',
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(length=16), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('user_id', sqlalchemy_utils.types.uuid.UUIDType(length=16), nullable=False),
    sa.Column('revoked', sa.Boolean(name='revoked'), nullable=False),
    sa.Column('issued_on', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('last_used_on', sa.DateTime(), nullable=True),
    sa.Column('access_token', sa.String(length=255), nullable=False),
    sa.Column('refresh_token', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_access_token')),
    sa.UniqueConstraint('name', 'user_id', name=op.f('uq_access_token_name'))
    )
    op.create_index(op.f('ix_access_token_access_token'), 'access_token', ['access_token'], unique=False)
    op.create_index(op.f('ix_access_token_refresh_token'), 'access_token', ['refresh_token'], unique=False)
    op.create_table('oauth_token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('token', sqlalchemy_utils.types.json.JSONType(), nullable=True),
    sa.Column('provider_id', sa.String(length=256), nullable=False),
    sa.Column('user_id', sqlalchemy_utils.types.uuid.UUIDType(length=16), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_oauth_token')),
    sa.UniqueConstraint('provider', 'provider_id', name=op.f('uq_oauth_token_provider')),
    sa.UniqueConstraint('provider_id', name=op.f('uq_oauth_token_provider_id'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('oauth_token')
    op.drop_index(op.f('ix_access_token_refresh_token'), table_name='access_token')
    op.drop_index(op.f('ix_access_token_access_token'), table_name='access_token')
    op.drop_table('access_token')
    # ### end Alembic commands ###
